/* Technical Editorial direction: the homepage is a concise field-guide gateway with deep ink, paper surfaces, Signal Teal wayfinding, and clear paths into focused pages. */
import { ArrowRight, ArrowUpRight, Check, Database, GraduationCap, Layers3, Network, Sparkles, Workflow } from "lucide-react";
import { Link } from "wouter";
import { engagementModels, industries, services, solutions } from "@/lib/siteData";
import { ConnectPanel, LOGO_URL, PageMeta, SectionLabel } from "@/components/SiteChrome";

const pathCards = [
  { href: "/services", label: "01 / SERVICES", title: "Build the foundation.", copy: "Engineering, analytics, cloud, AI, governance, and managed data services for the work in front of you.", icon: Workflow },
  { href: "/solutions", label: "02 / SOLUTIONS", title: "Choose the right pattern.", copy: "Explore practical architectures for warehouses, lakehouses, customer intelligence, migration, and AI readiness.", icon: Layers3 },
  { href: "/approach", label: "03 / APPROACH", title: "Make the path legible.", copy: "Understand how Zulubing frames the current state, target architecture, delivery sequence, and operating model.", icon: Network },
  { href: "/about/founder", label: "04 / FOUNDER", title: "Meet the builder.", copy: "Learn about Avnish Ojha, founder and CEO, and the product-building and data-engineering perspective behind Zulubing.", icon: Sparkles },
  { href: "/learning-mentorship", label: "05 / LEARNING", title: "Build your next capability.", copy: "Explore online and offline classes, 1:1 mentorship, career guidance, consultancy, and job-ready programme pathways.", icon: GraduationCap },
];

export default function Home() {
  return <>
    <PageMeta title="Engineering Data. Enabling Intelligence." description="Zulubing helps organizations build reliable data platforms, modernize analytics infrastructure, and turn complex data into actionable intelligence." path="/" />
    <main>
      <section className="home-hero relative overflow-hidden bg-ink text-white">
        <div className="hero-grid absolute inset-0 opacity-60" />
        <div className="container relative grid min-h-[680px] items-end gap-14 pb-24 pt-40 lg:grid-cols-[1.15fr_.85fr] lg:pb-28">
          <div className="max-w-4xl">
            <SectionLabel index="00" dark>DATA TECHNOLOGY PARTNER</SectionLabel>
            <h1 className="mt-7 max-w-4xl font-display text-6xl font-semibold leading-[0.94] tracking-[-0.065em] md:text-8xl">Engineering Data.<br /><span className="text-teal">Enabling Intelligence.</span></h1>
            <p className="mt-8 max-w-2xl text-lg leading-8 text-white/66 md:text-xl">Zulubing helps organizations build reliable data platforms, modernize their analytics infrastructure, and turn complex data into actionable intelligence.</p>
            <div className="mt-10 flex flex-wrap gap-3"><Link href="/talk-to-an-expert" className="button-primary">Bring Us the Hard Part <ArrowUpRight size={16} /></Link><Link href="/services" className="button-ghost-light">Review Service Paths <ArrowRight size={16} /></Link></div>
            <div className="mt-14 flex items-center gap-4 border-t border-white/15 pt-5 text-[11px] uppercase tracking-[0.15em] text-white/45"><span className="h-2 w-2 bg-teal" /> Build better data. Make better decisions.</div>
          </div>
          <div className="border-l border-teal/50 pl-5 lg:mb-1"><span className="mono-label text-teal">SYSTEM VIEW / 01</span><p className="mt-4 max-w-sm text-sm leading-7 text-white/55">A focused front door to the Zulubing field guide. Choose the path that matches the decision in front of you.</p><div className="mt-8 grid gap-3">{["Understand the current state", "Design the target architecture", "Build the data capability", "Operate and improve"].map((item, index) => <div key={item} className="flex items-center gap-3 border-b border-white/10 pb-3"><span className="font-mono text-xs text-teal">0{index + 1}</span><span className="text-sm font-semibold text-white/80">{item}</span></div>)}</div></div>
        </div>
        <div className="border-t border-white/10 bg-ink/80"><div className="container grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6">{["Cloud", "Data Engineering", "Analytics", "AI / ML", "Data Governance", "Managed Data"].map((item) => <div key={item} className="flex items-center gap-2 border-r border-white/10 px-3 py-4 text-[11px] font-semibold uppercase tracking-[0.08em] text-white/55 first:pl-0"><span className="h-1 w-1 bg-teal" />{item}</div>)}</div></div>
      </section>

      <section className="bg-paper py-20 md:py-28"><div className="container grid gap-12 lg:grid-cols-[.72fr_1.28fr]"><div><SectionLabel index="01">CHOOSE A PATH</SectionLabel><h2 className="section-title mt-5">A smaller page for the question you actually have.</h2><p className="mt-6 max-w-md text-base leading-8 text-slate-600">The detail now lives where it belongs: in focused pages with a clear next step, not one long scroll.</p></div><div className="grid border-l border-t border-slate-200 sm:grid-cols-2">{pathCards.map(({ href, label, title, copy, icon: Icon }) => <Link key={href} href={href} className="group border-b border-r border-slate-200 p-6 transition hover:border-teal hover:bg-white"><div className="flex items-center justify-between"><Icon size={18} className="text-cobalt" strokeWidth={1.5} /><span className="mono-label text-slate-400">{label}</span></div><h3 className="mt-10 font-display text-2xl font-semibold tracking-[-0.04em]">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{copy}</p><span className="mt-7 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.1em]">Open page <ArrowRight size={14} className="text-teal transition group-hover:translate-x-1" /></span></Link>)}</div></div></section>

      <section className="border-y border-slate-200 bg-[#e8efee] py-20 md:py-28"><div className="container grid gap-12 lg:grid-cols-[.72fr_1.28fr]"><div><SectionLabel index="02">CAPABILITY INDEX</SectionLabel><h2 className="section-title mt-5">The full service map, without the scroll.</h2><Link href="/services" className="text-link mt-8 inline-flex">Open all service pages <ArrowRight size={15} /></Link></div><div className="grid gap-0 border-t border-slate-300">{services.map((service, index) => <Link key={service.slug} href={`/services/${service.slug}`} className="group grid gap-3 border-b border-slate-300 py-5 md:grid-cols-[48px_1fr_1.2fr_auto] md:items-center"><span className="font-mono text-xs text-teal">0{index + 1}</span><span className="font-display text-lg font-semibold">{service.title}</span><span className="text-sm leading-6 text-slate-600">{service.summary}</span><ArrowRight size={16} className="text-cobalt transition group-hover:translate-x-1" /></Link>)}</div></div></section>

      <section className="bg-paper py-20 md:py-28"><div className="container grid gap-12 lg:grid-cols-[.72fr_1.28fr]"><div><SectionLabel index="03">FIELD GUIDE</SectionLabel><h2 className="section-title mt-5">Explore the surrounding context.</h2><p className="mt-5 max-w-md text-base leading-8 text-slate-600">Go deeper by architecture, operating environment, or way of working. Each path opens its own focused page.</p></div><div className="grid gap-4 sm:grid-cols-2">{[{ href: "/solutions", icon: Database, title: "Solutions", copy: `${solutions.length} architecture patterns` }, { href: "/industries", icon: Network, title: "Industries", copy: `${industries.length} operating contexts` }, { href: "/engagement-models", icon: Layers3, title: "Engagement models", copy: `${engagementModels.length} delivery shapes` }, { href: "/learning-mentorship", icon: GraduationCap, title: "Learning & mentorship", copy: "Classes, guidance, and 1:1 support" }, { href: "/resources", icon: Sparkles, title: "Resources", copy: "Practical field notes" }].map(({ href, icon: Icon, title, copy }) => <Link key={href} href={href} className="group flex items-center justify-between border border-slate-200 bg-white p-5 transition hover:border-teal"><span><span className="mono-label text-cobalt">OPEN / {title.toUpperCase()}</span><span className="mt-3 block font-display text-xl font-semibold">{title}</span><span className="mt-1 block text-sm text-slate-500">{copy}</span></span><Icon size={19} className="text-teal transition group-hover:translate-x-1" /></Link>)}</div></div></section>

      <section className="border-y border-slate-300/80 bg-[#eef4f2] py-20 text-ink md:py-24"><div className="container grid gap-10 lg:grid-cols-[1fr_.8fr] lg:items-center"><div><SectionLabel index="04">THE BUILDER</SectionLabel><h2 className="section-title mt-5 text-ink">Meet the person shaping the work.</h2><p className="mt-5 max-w-xl text-base leading-8 text-slate-600">Avnish Ojha is the founder and CEO of Zulubing, with around three years of industry experience and a focus on product building and data engineering.</p><Link href="/about/founder" className="text-link mt-8 inline-flex">Read the founder profile <ArrowRight size={15} /></Link></div><div className="flex items-center gap-5 border-l border-teal pl-6"><img src={LOGO_URL} alt="Zulubing AI" className="h-24 w-[170px] object-contain brightness-[0.28]" /><span className="font-mono text-[10px] uppercase tracking-[0.14em] text-slate-500">FOUNDER / CEO<br />ZULUBING</span></div></div></section>
      <ConnectPanel />
    </main>
  </>;
}
