/* Learning & Mentorship: a focused page for practical education, career conversations, and guided data capability building. */
import { ArrowRight, ArrowUpRight, BriefcaseBusiness, Check, Laptop, Mail, MapPin, Phone, Users } from "lucide-react";
import { Link } from "wouter";
import { ConnectPanel, PageHero, PageMeta, SectionLabel } from "@/components/SiteChrome";

const formats = [
  { icon: Laptop, label: "ONLINE CLASSES", title: "Learn from wherever you are.", copy: "Structured online sessions for learners and working professionals who want a clear path through data concepts, tools, projects, and practical decision-making." },
  { icon: Users, label: "OFFLINE SESSIONS", title: "Work together in the room.", copy: "Focused in-person sessions for cohorts, teams, and local groups that benefit from live explanation, shared exercises, and direct feedback." },
  { icon: BriefcaseBusiness, label: "1:1 MENTORSHIP", title: "Build with a closer feedback loop.", copy: "Individual guidance shaped around your current level, goals, portfolio, interview preparation, product idea, or next technical decision." },
];

const pathways = [
  { index: "01", title: "Career guidance", copy: "Clarify a practical next step: what to learn, how to sequence it, how to explain your work, and which questions to ask before committing time or money." },
  { index: "02", title: "Data consultancy", copy: "Bring a real project, product, dashboard, pipeline, or architecture question. We can use a focused working session to understand the context and outline possible paths." },
  { index: "03", title: "Job-ready programme", copy: "A guided preparation path built around fundamentals, applied work, project communication, interview readiness, and the habits needed to contribute on a real data team." },
  { index: "04", title: "Product-building mentorship", copy: "Turn an idea into a clearer product and data plan by working through the problem, users, workflow, technical shape, and the smallest useful build." },
];

const tracks = [
  { title: "Data Analytics", copy: "Build fluency in asking useful questions, working with data, shaping metrics, communicating insight, and developing a portfolio that shows your reasoning." },
  { title: "Data Engineering", copy: "Develop a stronger foundation in data systems, pipelines, modeling, quality, orchestration, cloud concepts, and the engineering choices behind dependable platforms." },
];

export default function LearningMentorshipPage() {
  return <>
    <PageMeta title="Learning & Mentorship" description="Explore Zulubing’s online and offline classes, 1:1 mentorship, career guidance, consultancy, and job-ready programmes." path="/learning-mentorship" />
    <PageHero eyebrow="10 / LEARNING & MENTORSHIP" title="Build the capability to move forward." description="Practical learning and mentorship for people who want to understand data work, build stronger products, and make a more confident next career or technical move.">
      <div className="mt-6 flex flex-wrap items-center gap-5 text-xs font-semibold text-slate-500"><span className="flex items-center gap-2"><span className="h-1.5 w-1.5 bg-teal" /> ONLINE + OFFLINE</span><span className="flex items-center gap-2"><span className="h-1.5 w-1.5 bg-teal" /> 1:1 GUIDANCE</span><span className="flex items-center gap-2"><span className="h-1.5 w-1.5 bg-teal" /> DISCOVERY-LED</span></div>
    </PageHero>
    <main className="bg-paper">
      <section className="border-b border-slate-200 py-20 md:py-28"><div className="container grid gap-12 lg:grid-cols-[0.72fr_1.28fr]"><div><SectionLabel index="01">THE INTENT</SectionLabel><h2 className="section-title mt-5">Less noise. More useful practice.</h2></div><div className="text-base leading-8 text-slate-600"><p>Learning data and technology is easier when the path connects concepts to real work. Zulubing’s sessions are designed to help you understand the why behind the tools, practice the underlying thinking, and choose a next step that fits your context.</p><p className="mt-5">This is not a promise of instant placement or a fixed syllabus for every learner. The right format, schedule, depth, and fee are confirmed after we understand your starting point and what you are trying to achieve.</p></div></div></section>
      <section className="bg-[#e8efee] py-20 md:py-28"><div className="container"><SectionLabel index="02">WAYS TO WORK TOGETHER</SectionLabel><h2 className="section-title mt-5 max-w-3xl">Choose a format that matches the work you need to do.</h2><div className="mt-10 grid gap-4 lg:grid-cols-3">{formats.map(({ icon: Icon, label, title, copy }) => <article key={label} className="border border-slate-300 bg-white p-7"><div className="flex items-center justify-between"><Icon size={20} className="text-cobalt" strokeWidth={1.5} /><span className="mono-label text-teal">{label}</span></div><h3 className="mt-12 font-display text-2xl font-semibold tracking-[-0.04em]">{title}</h3><p className="mt-4 text-sm leading-7 text-slate-600">{copy}</p></article>)}</div></div></section>
      <section className="py-20 md:py-28"><div className="container grid gap-12 lg:grid-cols-[0.72fr_1.28fr]"><div><SectionLabel index="03">FOCUSED PATHWAYS</SectionLabel><h2 className="section-title mt-5">Support for the decision in front of you.</h2><p className="mt-6 text-base leading-8 text-slate-600">Start with a specific question and we can shape the right conversation around it. Sessions can be educational, advisory, practical, or a combination of the three.</p></div><div className="grid gap-0 border-t border-slate-200">{pathways.map((pathway) => <div key={pathway.index} className="grid gap-4 border-b border-slate-200 py-6 sm:grid-cols-[52px_1fr]"><span className="font-mono text-xs text-teal">{pathway.index}</span><div><h3 className="font-display text-xl font-semibold tracking-[-0.03em]">{pathway.title}</h3><p className="mt-2 max-w-2xl text-sm leading-7 text-slate-600">{pathway.copy}</p></div></div>)}</div></div></section>
      <section className="border-y border-slate-200 bg-[#f7f9f8] py-20 md:py-28"><div className="container"><div className="grid gap-12 lg:grid-cols-[0.72fr_1.28fr]"><div><SectionLabel index="04">COURSE ENQUIRIES</SectionLabel><h2 className="section-title mt-5">For data analytics and data engineering courses, start with an email.</h2><p className="mt-6 text-base leading-8 text-slate-600">Tell us where you are starting, what you want to learn, whether you prefer online or offline sessions, and the timeline you have in mind. We will reply with the most relevant next step.</p><a href="mailto:development.zulubing@gmail.com?subject=Data%20Course%20Enquiry" className="button-primary mt-8 inline-flex">Email about a course <ArrowUpRight size={15} /></a></div><div className="grid gap-4 sm:grid-cols-2">{tracks.map((track) => <article key={track.title} className="border border-slate-200 bg-white p-7"><span className="mono-label text-cobalt">DISCUSSION TRACK</span><h3 className="mt-5 font-display text-2xl font-semibold tracking-[-0.04em]">{track.title}</h3><p className="mt-4 text-sm leading-7 text-slate-600">{track.copy}</p><a href={`mailto:development.zulubing@gmail.com?subject=${encodeURIComponent(`${track.title} Course Enquiry`)}`} className="text-link mt-7 inline-flex">Connect by email <ArrowRight size={14} /></a></article>)}</div></div></div></section>
      <section className="border-y border-slate-300/80 bg-[#eef4f2] py-20 text-ink md:py-24"><div className="container grid gap-10 lg:grid-cols-[0.8fr_1.2fr] lg:items-end"><div><SectionLabel index="05">START WITH CONTEXT</SectionLabel><h2 className="section-title mt-5 text-ink">A useful learning plan begins with an honest starting point.</h2><p className="mt-6 max-w-xl text-base leading-8 text-slate-600">Share your goals, current experience, preferred format, and the kind of support you are looking for. We can then decide whether a class, mentorship session, consultancy conversation, or job-ready programme is the right fit.</p></div><div className="border-l border-teal pl-6"><div className="grid gap-4 text-sm text-slate-700"><div className="flex items-start gap-3"><Mail size={16} className="mt-0.5 text-teal" /><a href="mailto:development.zulubing@gmail.com" className="hover:text-cobalt">development.zulubing@gmail.com</a></div><div className="flex items-start gap-3"><Phone size={16} className="mt-0.5 text-teal" /><a href="tel:+918585904477" className="hover:text-cobalt">+91 8585904477</a></div><div className="flex items-start gap-3"><MapPin size={16} className="mt-0.5 text-teal" /><span>New Delhi, India</span></div></div><div className="mt-7 flex flex-wrap gap-3"><Link href="/contact" className="button-primary">Ask about a session <ArrowUpRight size={15} /></Link><Link href="/about/founder" className="button-ghost-dark">Meet the builder <ArrowRight size={15} /></Link></div></div></div></section>
    </main>
    <ConnectPanel compact />
  </>;
}
